- name: Pull flannel image
  docker_image: name={{ flannel_docker_registry }}/coreos/flannel tag=v{{ flannel_version }}-amd64

- name: Deploy flannel
  run_once: true
  include_tasks: k8s.yml

- name: Wait for flannel env file - 30 seconds
  wait_for: path=/var/run/flannel/subnet.env timeout=30
- name: Read cidr from flannel env file
  command: grep FLANNEL_SUBNET= /var/run/flannel/subnet.env
  register: flannel_subnet_result
  changed_when: false
- name: Read flannel subnet
  set_fact: flannel_subnet={{ flannel_subnet_result.stdout.split('=')[1] }}
- name: Read flannel IP
  set_fact: flannel_ip={{ flannel_subnet.split('/')[0] }}
- name: Configure docker for flannel subnet
  lineinfile: path=/etc/sysconfig/docker regexp=^DOCKER_BIP= line="DOCKER_BIP=--bip {{ flannel_subnet }}"
- name: Restart docker service
  service: name={{ item.service }} state={{ item.state }}
  when: ansible_docker0 is not defined or ansible_docker0.ipv4.address != flannel_ip
  notify: wait for apiserver
  loop:
  - { service: kubelet, state: stopped }
  - { service: docker, state: restarted }
  - { service: kubelet, state: started }
